{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>Unnamed: 0</th>\n",
       "      <th>Source</th>\n",
       "      <th>worth</th>\n",
       "      <th>worthChange</th>\n",
       "      <th>realTimePosition</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>4656</td>\n",
       "      <td>52</td>\n",
       "      <td>Technology  ==&gt; Amazon</td>\n",
       "      <td>112.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>1874</td>\n",
       "      <td>53</td>\n",
       "      <td>Technology  ==&gt; Microsoft</td>\n",
       "      <td>90.0</td>\n",
       "      <td>-0.001</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>6703</td>\n",
       "      <td>54</td>\n",
       "      <td>Finance and Investments  ==&gt; Berkshire Hathaway</td>\n",
       "      <td>84.0</td>\n",
       "      <td>-0.002</td>\n",
       "      <td>3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2637</td>\n",
       "      <td>55</td>\n",
       "      <td>Fashion &amp; Retail  ==&gt; LVMH</td>\n",
       "      <td>72.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>8242</td>\n",
       "      <td>56</td>\n",
       "      <td>Technology  ==&gt; Facebook</td>\n",
       "      <td>71.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2203</th>\n",
       "      <td>1711</td>\n",
       "      <td>2255</td>\n",
       "      <td>Fashion &amp; Retail  ==&gt; fashion, entertainment</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2134</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2204</th>\n",
       "      <td>3538</td>\n",
       "      <td>2256</td>\n",
       "      <td>Manufacturing  ==&gt; electrical equipment</td>\n",
       "      <td>1.0</td>\n",
       "      <td>na</td>\n",
       "      <td>2134</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2205</th>\n",
       "      <td>7797</td>\n",
       "      <td>2257</td>\n",
       "      <td>Manufacturing  ==&gt; electrical equipment</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1856</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2206</th>\n",
       "      <td>3123</td>\n",
       "      <td>2258</td>\n",
       "      <td>Manufacturing  ==&gt; printed circuit boards</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>1978</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2207</th>\n",
       "      <td>7030</td>\n",
       "      <td>2259</td>\n",
       "      <td>Diversified  ==&gt; diversified</td>\n",
       "      <td>1.0</td>\n",
       "      <td>na</td>\n",
       "      <td>1978</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2208 rows × 6 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "        id  Unnamed: 0                                           Source  \\\n",
       "0     4656          52                           Technology  ==> Amazon   \n",
       "1     1874          53                        Technology  ==> Microsoft   \n",
       "2     6703          54  Finance and Investments  ==> Berkshire Hathaway   \n",
       "3     2637          55                       Fashion & Retail  ==> LVMH   \n",
       "4     8242          56                         Technology  ==> Facebook   \n",
       "...    ...         ...                                              ...   \n",
       "2203  1711        2255     Fashion & Retail  ==> fashion, entertainment   \n",
       "2204  3538        2256          Manufacturing  ==> electrical equipment   \n",
       "2205  7797        2257          Manufacturing  ==> electrical equipment   \n",
       "2206  3123        2258        Manufacturing  ==> printed circuit boards   \n",
       "2207  7030        2259                     Diversified  ==> diversified   \n",
       "\n",
       "       worth worthChange  realTimePosition  \n",
       "0     112.0          0.0                 1  \n",
       "1      90.0       -0.001                 2  \n",
       "2      84.0       -0.002                 3  \n",
       "3      72.0          0.0                 4  \n",
       "4      71.0          0.0                 5  \n",
       "...      ...         ...               ...  \n",
       "2203    1.0          0.0              2134  \n",
       "2204    1.0           na              2134  \n",
       "2205    1.0          0.0              1856  \n",
       "2206    1.0          0.0              1978  \n",
       "2207    1.0           na              1978  \n",
       "\n",
       "[2208 rows x 6 columns]"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#ACQUIRE bussines_info\n",
    "\n",
    "import sqlite3\n",
    "import pandas as pd\n",
    "import re\n",
    "\n",
    "df = sqlite3.connect('/Users/MIGUEL/Desktop/CLAB1/Ironhack-Module-1-Project---Pipelines-/data/raw/Miguel318.db')\n",
    "\n",
    "dfBI = pd.read_sql_query(\"SELECT * FROM business_info\", df)\n",
    "    \n",
    "#WRANGLING bussines_info\n",
    "    #drop realTimeWorth - 100% nulls\n",
    "\n",
    "dfBI.drop(['realTimeWorth'], axis='columns', inplace=True)\n",
    "\n",
    "dfBI.replace({\"BUSD\": ' '})\n",
    "\n",
    "\n",
    "#regex - separar valores numericos \n",
    "dfBI.worth.replace('[BUSD]+$', '', regex=True, inplace=True)\n",
    "dfBI.worthChange.replace('[millions USD]+$', '', regex=True, inplace=True)\n",
    "\n",
    "\n",
    "dfBI\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
